{% set name = "h2o-lightwave-web" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/h2oai/wave/archive/v{{ version }}.tar.gz
  sha256: 83a631c38301d0cadbb15c7e94a652fb8eadff0d9442cff917dd84173df95028

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./py/h2o_lightwave_web -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - h2o_lightwave_web
  commands:
    - pip check
  requires:
    - pip

about:
  description: Web assets for H2O Lightwave.
  dev_url: https://github.com/h2oai/wave/tree/main/py/h2o_lightwave_web
  doc_url: https://wave.h2o.ai/
  home: https://wave.h2o.ai/
  summary: Web assets package for H2O Lightwave apps.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - py/h2o_lightwave_web/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
