{% set name = "h2o-lightwave-web" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/h2oai/wave/archive/v{{ version }}.tar.gz
  sha256: 363dc78b74f28e5f2c57ab730ca3d0c25c550923804d7f4757f772ba4b07a0a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./py/h2o_lightwave_web -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - h2o_lightwave_web
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  description: Web assets for H2O Lightwave.
  dev_url: https://github.com/h2oai/wave/tree/main/py/h2o_lightwave_web
  doc_url: https://wave.h2o.ai/
  home: https://wave.h2o.ai/
  summary: Web assets package for H2O Lightwave apps.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - py/h2o_lightwave_web/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
